/*eslint-disable camelcase*/
/*eslint quotes: [2, "double"]*/
/*global Skype*/

// For messages that have different wording for business, use the same key as the consumer counterpart but with a "_4b" suffix.
// Then use the knockout binding "businessAwareL10n" instead of "l10n" in the UI view for messages that have business variants.
// With the business aware binding, _4b messages will be automatically used if the useBusinessWording feature flag is active.
// Example:
//  newbee_text_cta: "Find your friends by entering their name or email in the Search Skype field.",
//  newbee_text_cta_4b: "Find your co-workers by entering their name in the Search field.",

Skype && Skype.WebExperience && Skype.WebExperience.setTranslations({

    splashScreen_text_logo_4b: "Skype for Business",
    splashScreen_text_loading: "يتم الآن التحميل...",
    splashScreen_text_signingIn: "يتم تسجيل الدخول...",
    splashScreen_text_signingIn_wac: "جارٍ الانضمام إلى الدردشة...",
    splashScreen_text_loading_skype: "يتم تحميل Skype",
    splashScreen_text_loading_skype_4b: "يتم تحميل Skype for Business",
    splashScreen_text_signing_into_skype: "يتم تسجيل الدخول إلى Skype",
    splashScreen_text_signing_into_skype_4b: "يتم تسجيل الدخول إلى Skype for Business",
    splashScreen_signedOut_title: "يرجى تسجيل الدخول لبدء الاستخدام.",
    splashScreen_signedOut_title_wac: "يرجى الانضمام إلى الدردشة للبدء.",
    splashScreen_signedOut_reauth_needed_title: "تم تسجيل خروجك",
    splashScreen_signedOut_reauth_needed_description: "قم بتسجيل الدخول باستخدام حساب Microsoft الخاص بك لتتمكن من متابعة استخدام Skype.",
    splashScreen_disconnected_title: "تم قطع اتصالك.",
    splashScreen_disconnected_description: "يرجى محاولة تسجيل الدخول مرة أخرى أو تحديث الصفحة.",
    splashScreen_disconnected_description_wac: "يرجى محاولة الانضمام إلى الدردشة من جديد أو تحديث الصفحة.",
    splashScreen_signInFailed_title: "تعذر علينا تسجيل دخولك.",
    splashScreen_signInFailed_title_wac: "تعذر علينا ضمك إلى الدردشة.",
    splashScreen_signInFailed_title_security_validation: "أجرِ مكالمات فيديو ومكالمات صوتية باستخدام Skype لويب.",
    splashScreen_signInFailed_description: "يرجى محاولة تسجيل الدخول مرة أخرى أو تحديث الصفحة.",
    splashScreen_signInFailed_description_wac: "يرجى محاولة الانضمام إلى الدردشة من جديد أو تحديث الصفحة.",
    splashScreen_signInFailed_description_exceeded_endpoints: "تخطى Skype عدد نقاط النهاية المسموح به.",
    splashScreen_signInFailed_description_age_restriction: "عذراً، لا يمكنك استخدام Skype بسبب قيود العمر.",
    splashScreen_signInFailed_aad_description: "يرجى محاولة تسجيل الدخول مرة أخرى أو تحديث الصفحة.",
    splashScreen_learn_more: "معرفة المزيد",

    splashScreen_signIn_button: "تسجيل الدخول",
    splashScreen_signIn_button_wac: "الانضمام إلى الدردشة",
    splashScreen_signInExternal_button: "تسجيل الدخول باستخدام حساب Microsoft",

    splashScreen_signInExternal_title: "تتم محاولة تسجيل الدخول.",
    splashScreen_signInExternal_description: "يرجى إدخال حسابك وكلمة المرور عندما يُطلب منك ذلك.",

    unsupportedBrowser_title: "يرجى تحديث المستعرض للبدء باستخدام Skype.",

    skypeUnavailable_title: "نواجه حالياً مشاكل في الخادم. يعمل Skype على حل المشاكل وسيصبح متوفراً من جديد بعض قليل.",

    aggressiveLinking_intro_title: "إلقاء التحية على Outlook",
    aggressiveLinking_intro_description: "يمكنك الآن الاتصال بجهات الاتصال في Outlook والدردشة معها مباشرةً من علبة الوارد، وكل ذلك مجاناً.",
    aggressiveLinking_intro_continue: "متابعة",
    aggressiveLinking_intro_signin: "هل تسخدم Skype؟ {link_start}سجل دخولك{link_end}",
    aggressiveLinking_intro_legal: "من خلال المتابعة، توافق على {link_tou_start}شروط استخدام Skype‏‏{link_tou_end} و{link_privacy_start}سياسة الخصوصية{link_privacy_end}.",

    one_account_link: "هل تستخدم Skype بالفعل؟ {link_start}تعرف على المزيد{link_end}",

    input_placeholder_searchSkype: "بحث في Skype",
    input_searchSkype_ariaLabel: "ابحث في المحادثة. اكتب اسم المجموعة أو جهة الاتصال.",
    input_searchSkype_ariaLabel_4b: "ابحث في المحادثة. اكتب اسم جهة الاتصال.",
    input_searchSkypeDirectory_ariaLabel: "بحث في دليل Skype",
    clear_search_input_label: "مسح البحث",

    button_text_newChat: "دردشة جديدة",
    button_text_new: "جديد",
    button_text_dialpad: "الاتصال بالهواتف",
    input_text_skypeOut: "إدخال اسم أو رقم",
    input_text_skypeOut_short: "إدخال الرقم",
    clear_phonenumber_input_label: "مسح رقم الهاتف",

    select_placeholder_skypeOut: "اختيار البلد/المنطقة",
    label_text_participant: "{count} مشارك",
    label_text_participant_few: "{count} من المشاركين",
    label_text_participant_many: "{count} من المشاركين",
    area_text_insertText: "اكتب رسالة هنا",
    area_text_insertTextWithCommands: "اكتب رسالة هنا أو {helpCommand} للحصول على قائمة الأوامر",
    area_text_agent_insertText: "عذراَ، لا يمكنك الرد الآن",
    area_text_insertTextNonMember: "لقد غادرت هذه المجموعة.",
    label_text_insertText_oneToOne: "إدخال الدردشة، محادثة مع {displayName}. {quotedText}",
    label_text_insertText_group: "إدخال الدردشة، محادثة مع {displayName}،‏ {participantsText}. {quotedText}",
    label_text_conversationsLoading: "يتم الآن تحميل المحادثات الأخيرة...",
    label_text_conversationsLoadNone: "لا توجد محادثات أخيرة",
    label_text_currentCallHeading: "المكالمة الحالية",
    label_text_openConversation: "فتح محادثة مع {displayName}",
    label_text_from: "من: ",
    label_text_clearedText: "تم مسح ناحية النص",
    label_text_clearedQuotes: "تم مسح الرسالة المقتبسة",

    label_quoted_message: "رسالة مقتبسة {quotesContent} من {senderName} في {time}",

    today: "اليوم",
    yesterday: "الأمس",
    olderThanAWeek: "أقدم من أسبوع",

    duration_days: "يوم {count}",
    duration_days_few: "{count} من الأيام",
    duration_days_many: "{count} من الأيام",
    duration_hours: "ساعة {count}",
    duration_hours_few: "{count} من الساعات",
    duration_hours_many: "{count} من الساعات",
    duration_minutes: "دقيقة {count}",
    duration_minutes_few: "{count} من الدقائق",
    duration_minutes_many: "{count} من الدقائق",
    duration_moment: "لحظة",

    content_search_conversation_title_days: "منذ يوم {count} في <b>{conversationTitle}</b>",
    content_search_conversation_title_days_few: "منذ {count} من الأيام في <b>{conversationTitle}</b>",
    content_search_conversation_title_days_many: "منذ {count} من الأيام في <b>{conversationTitle}</b>",
    content_search_conversation_title_hours: "منذ ساعة {count} في <b>{conversationTitle}</b>",
    content_search_conversation_title_hours_few: "منذ {count} من الساعات في <b>{conversationTitle}</b>",
    content_search_conversation_title_hours_many: "منذ {count} من الساعات في <b>{conversationTitle}</b>",
    content_search_conversation_title_minutes: "منذ دقيقة {count} في <b>{conversationTitle}</b>",
    content_search_conversation_title_minutes_few: "منذ {count} من الدقائق في <b>{conversationTitle}</b>",
    content_search_conversation_title_minutes_many: "منذ {count} من الدقائق في <b>{conversationTitle}</b>",
    content_search_conversation_title_moment: "منذ لحظة في <b>{conversationTitle}</b>",
    content_search_header: "الرسائل",
    content_search_aria: "محادثة موضوعها {topic}.",
    content_search_additional_results: "إظهار المزيد من الرسائل",

    contact_isSelected: "محدد",

    label_text_headerMenuRemoveGroup: "إزالة من المجموعة",
    label_text_headerMenuChat: "دردشة",
    label_text_headerMenuInstantMessage: "رسالة فورية",

    button_text_discover_agents: "اكتشاف الحسابات الآلية",
    label_text_discover_agents_page_header: "روبوتات",
    label_text_discover_agents_page_hint: "تلميح: يمكنك التفاعل مع الحسابات الآلية عبر الضغط عليها وإضافتها إلى جهات اتصالك.",
    label_text_discover_agents_page_zero_results_text_part_1: "يبدو أنه سبق واتصلت بكل الحسابات الآلية. يمكنك التفاعل معها من صفحة \"جهات الاتصال\" أو عبر البحث عنها.",
    label_text_discover_agents_page_zero_results_text_part_2: "نضيف دائماً حسابات آلية جديدة، لذا يرجى التحقق مجدداً من هذه الصفحة قريباً.",

    label_text_contact_profile_details: "تفاصيل جهة الاتصال",
    label_text_contact_profile_skype_name: "Skype",
    label_text_contact_profile_skype_for_business_name: "Skype for Business",
    label_text_contact_profile_information: "معلومات",
    label_text_contact_profile_location: "الموقع",
    label_text_contact_profile_birthday: "تاريخ الميلاد",
    label_text_contact_profile_gender: "النوع الاجتماعي",
    label_text_contact_profile_language: "اللغة",
    label_text_contact_profile_agent_description: "الوصف",
    label_text_contact_profile_agent_author: "المؤلف",
    label_text_contact_profile_agent_certification: "الشهادة",
    label_text_contact_profile_agent_rating: "معدل التصنيف",
    label_text_view_profile_menu_item: "عرض ملف التعريف",

    label_text_agent_profile_label_agentid: "الحساب الآلي",
    label_text_agent_profile_label_skype_certified: "معتمد من Skype",
    label_text_agent_profile_label_author: "تم الإنشاء من قِبل",
    label_text_agent_profile_label_description: "حول",
    label_text_agent_profile_label_website: "موقع ويب",
    label_text_agent_profile_label_privacy: "الخصوصية",
    label_text_agent_profile_value_privacy: "سيتوفر لدى هذا الحساب الآلي إمكانية الوصول إلى اسم العرض الخاص بك والمنطقة واللغة وأي رسائل أو محتويات تشاركها أنت أو المشاركون الآخرون مع الحساب الآلي.",
    label_text_agent_profile_value_privacy_autoplay: "ويمكنه أيضاً تشغيل محتويات الوسائط من الجهات الخارجية تلقائياً",
    label_text_agent_profile_link_text_terms_of_service: "شروط الخدمة",
    label_text_agent_profile_link_text_privacy_statement: "بيان الخصوصية",
    label_text_agent_profile_label_rating: "التصنيف",
    label_text_agent_profile_label_capabilities: "إليك ما يمكنك فعله بواسطة هذا الحساب الآلي",
    label_text_agent_profile_label_extra_info: "مزيد من المعلومات",
    label_text_agent_profile_capabilities_none: "قراءة التحديثات من هذا الحساب الآلي",
    label_text_agent_profile_capabilities_join_char: "، و",
    label_text_agent_profile_capabilities_audio_send: "إجراء مكالمات صوتية",
    label_text_agent_profile_capabilities_video_send: "إجراء مكالمات فيديو",
    label_text_agent_profile_capabilities_im_send: "إرسال رسائل فورية",
    label_text_agent_profile_capabilities_screen_sharing: "مشاركة الشاشات",
    label_text_agent_profile_capabilities_gvc: "إجراء مكالمات فيديو جماعية",
    label_text_agent_profile_capabilities_group_chat: "إضافة الحساب الآلي إلى الدردشات الجماعية",
    label_text_agent_profile_capabilities_group_chat_mention_only_mode: "(يتلقى هذا الحساب الآلي الرسائل المرسلة إليه باستخدام <i>@{botName}</i>)",
    label_text_agent_profile_capabilities_group_chat_all_messages_mode: "(يتلقى هذا الحساب الآلي جميع الرسائل والمحتويات المرسلة في المجموعة)",
    label_text_agent_profile_capabilities_file_send: "إرسال ملفات",
    label_text_agent_profile_capabilities_contact_send: "إرسال جهات اتصال",
    label_text_agent_profile_capabilities_videomessage_send: "إرسال رسائل فيديو",
    label_text_agent_profile_capabilities_audiomessage_send: "إرسال رسائل صوتية",
    label_text_agent_profile_capabilities_mediamessage_send: "إرسال رسائل وسائط",
    label_text_agent_profile_capabilities_photo_send: "إرسال صور",
    label_text_agent_profile_capabilities_moji_send: "إرسال Mojis",
    label_text_agent_profile_capabilities_location_send: "مشاركة الموقع",
    label_text_agent_profile_capabilities_media_autoplay: "تشغيل محتويات الوسائط تلقائياً",

    label_text_blockContact: "حظر جهة الاتصال",
    label_text_block_agent: "حظر الحساب الآلي",
    label_text_blockContact_with_name: "حظر {name}",
    label_text_unblockContact: "إلغاء حظر جهة الاتصال",
    label_text_unblock_agent: "إلغاء حظر الحساب الآلي",
    label_text_unblockContact_with_name: "إلغاء حظر {name}",
    label_text_deleteContact: "حذف جهة الاتصال",
    label_text_delete_agent: "حذف الحساب الآلي",

    label_text_call_skype_audio: "مكالمة Skype",
    label_text_call_skype_video: "إجراء مكالمة فيديو",
    label_text_send_message: "إرسال رسالة",
    label_text_call: "مكالمة",
    label_text_call_phone_number: "الاتصال بـ ({phoneNumber})",
    label_text_call_phone_number_home: "الاتصال بهاتف المنزل ({phoneNumber})",
    label_text_call_phone_number_work: "الاتصال بهاتف المكتب ({phoneNumber})",
    label_text_call_phone_number_cell: "الاتصال بالهاتف المحمول ({phoneNumber})",
    label_text_call_phone_number_type: "الاتصال بـ {phoneNumberType} ({phoneNumber})",
    label_text_phone_number_type_home: "الصفحة الرئيسية",
    label_text_phone_number_type_work: "المكتب",
    label_text_phone_number_type_cell: "الهاتف المحمول",
    label_text_phone_number_type_other: "غير ذلك",

    modal_blockContact_text_aria_label: "حظر جهة الاتصال",
    modal_block_agent_text_aria_label: "حظر الحساب الآلي",
    modal_blockContact_text_title: "هل تريد بالتأكيد حظر {displayName}؟",
    modal_blockContact_text_message: "لن يتمكن من الاتصال بك ولن يظهر في قائمة جهات اتصالك.",
    modal_block_contact_text_learn_more_link: "معرفة المزيد",
    modal_blockContact_text_reportAbuse: "الإبلاغ عن الإساءة من هذا الشخص",
    modal_block_agent_text_reportAbuse: "الإبلاغ عن إساءة صادرة عن هذا الحساب الآلي",
    select_placeholder_report_abuse_reason: "تحديد سبب...",
    report_abuse_reason_option_spam: "محتوى عشوائي",
    report_abuse_reason_option_pornography: "يحتوي على العري أو المواد الإباحية",
    report_abuse_reason_option_child_exploitation: "استغلال الأطفال",
    report_abuse_reason_option_harassment: "تحرش أو تهديدات",

    modal_deleteContact_text_aria_label: "حذف جهة الاتصال",
    modal_delete_agent_text_aria_label: "حذف الحساب الآلي",
    modal_deleteContact_text_title: "هل تريد بالتأكيد حذف {displayName}؟",
    modal_deleteContact_text_message: "ستتم إزالة {displayName} من قائمة جهات الاتصال الخاصة بك.",

    modal_device_disabled_chrome_title: "لإجراء مكالمات Skype، يرجى السماح لـ Google Chrome بالوصول إلى الكاميرا والميكروفون لديك.",
    modal_device_disabled_chrome_text: "انقر فوق أيقونة {image} في شريط العناوين للسماح بالوصول إلى الكاميرا والميكروفون.",
    modal_device_disabled_edge_title: "لإجراء مكالمات Skype، يرجى السماح لـ Microsoft Edge بالوصول إلى الكاميرا والميكروفون لديك.",
    modal_device_disabled_edge_text: "يمكنك ببساطة إعادة تحميل هذه الصفحة ومحاولة إجراء مكالمة أخرى، ثم تحديد \"نعم\" عند مطالبتك بالسماح بالوصول.",

    header_text_close: "إغلاق",
    header_text_participantsOthersCanJoin: "{count} من المشاركين، يستطيع الآخرون الانضمام",
    header_text_participantsOthersCanJoin_few: "{count} من المشاركين، يمكن أن ينضم آخرون",
    header_text_participantsOthersCanJoin_many: "{count} من المشاركين، يمكن أن ينضم آخرون",
    header_text_shareThisGroup: "مشاركة هذه المجموعة",
    header_text_groupSettings: "إعدادات المجموعة",
    header_text_copyLink: "نسخ الارتباط",
    header_text_copied: "تم النسخ",
    header_text_inviteViaEmail: "دعوة بالبريد الإلكتروني",
    header_text_adminSettings: "إدارة المجموعة",
    header_text_makeHistoryAvailable: "جعل محفوظات الدردشة متوفرة للمنضمين الجدد",
    header_text_joinViaLink: "إنشاء ارتباط ليتمكن أي شخص من الانضمام",
    header_text_allowOthersToJoin: "السماح للآخرين بالانضمام باستخدام ارتباط",
    header_text_othersCanJoin: "بإمكان الآخرين الانضمام باستخدام ارتباط",
    header_text_muteConversation: "إعلامات المحادثات",
    header_secondary_text_muteConversation: "إعلامي عند حدوث أمر جديد",
    header_narrator_notifications_on: "تشغيل الإعلامات",
    header_narrator_notifications_off: "إيقاف تشغيل الإعلامات",
    header_text_admin: "المسؤول",
    header_text_admin_4b: "مقدم العرض",
    header_text_guest: "ضيف",

    spaces_default_name: "محادثة بلا عنوان",
    spaces_tooltip_text: "يمكنك دعوة أشخاص آخرين عبر إرسال هذا الارتباط إليهم، حتى إن كانوا لا يستخدمون Skype.",
    spaces_email_subject: "أنا جاهز للدردشة على Skype",
    spaces_joining_disabled_message_start: "تشغيل <i>\"إنشاء ارتباط ليتمكن أي شخص من الانضمام\"</i> من ",
    spaces_joining_disabled_anchor_text: "ملف التعريف ",
    spaces_joining_disabled_message_end: "للحصول على ارتباط يمكنك مشاركته.",

    spaces_email_greeting: "مرحباً،",
    spaces_email_joinMe: "لقد أنشأتُ مجموعةً على Skype لنتمكن من الدردشة والمشاركة والتعاون.",
    spaces_email_link: "الانضمام عبر النقر فوق الارتباط",
    spaces_welcomeTitle: "تم إعداد محادثتك بالكامل",
    spaces_welcomeMessage: "مشاركة الصور والرسائل والمزيد غيرها مع الجميع هنا أو دعوة المزيد من الأشخاص أيضاً عبر مشاركة هذا الارتباط معهم",
    spaces_welcomeMessageWithoutLink: "مشاركة الصور والرسائل والمزيد غيرها مع الجميع هنا",
    spaces_welcomeRenameBtnTitle: "إعادة تسمية المحادثة",
    spaces_welcomeRenameBtnMessage: "اجعل محادثتك فريدةً من نوعها",
    spaces_welcomeSettingsBtnTitle: "إعدادات",
    spaces_welcomeSettingsBtnMessage: "إدارة محادثتك",
    spaces_anyoneElse: "هل تريد دعوة شخص آخر؟ أرسل إليه ارتباطاً",
    spaces_conversation_renamed_success: "تمت إعادة تسمية المحادثة إلى {conversationName}.",

    input_placeholder_addAnotherContact: "إضافة جهة اتصال أخرى",
    input_placeholder_typeContactName: "كتابة اسم جهة الاتصال",

    message_text_hasLeftConversation: "تمت مغادرة هذه المحادثة من قبل {participant}",
    message_text_wasRemovedFromConversation: "تمت إزالة {removedParticipant} من هذه المحادثة من قبل {participant}",
    message_text_youWereRemovedFromConversation: "تمت إزالتك من هذه المحادثة",
    message_text_joinedConversation: "تم الانضمام إلى هذه المحادثة من قبل {participant}",
    message_text_joinConversationFailed: "تعذر على {participant} الانضمام إلى هذه المحادثة",
    message_text_meJoinedConversation_one: "{participant} يدردش",
    message_text_meJoinedConversation_more: "{participants} و{participant} يدردشون",
    message_text_wasAddedToConversation: "قام {participant} بإضافة {contact} إلى هذه المحادثة.",
    message_text_botWasAddedToConversation: "للدردشة، ابدأ رسالتك بـ <i>@{botName}</i>. تم إخفاء كل الرسائل الأخرى في المجموعة من الحساب الآلي.",
    message_text_joiningConversationWithBots: "<b>تتم المشاركة في هذه المجموعة من قِبل {botName}‏</b></br>. للدردشة، ابدأ رسالتك بـ <i>@{botName}</i>. تم إخفاء كل الرسائل الأخرى في المجموعة من الحساب الآلي.",
    message_text_joiningConversationWithBotsV2: "يشارك <b>{botName} في هذه المجموعة.</b></br>",
    message_text_addedBotGroupConversation_privateMode: "<b>يتلقى {botName} الرسائل المرسلة إليه مباشرة باستخدام <i>@{botName}</i>.",
    message_text_addedBotGroupConversation_allMessagesMode: "<b>يتلقى {botName} جميع الرسائل والمحتويات المرسلة في هذه الدردشة.",
    message_text_roleUpdated: "تم تحديث دور {whom} إلى {role} من قبل {who}",
    message_text_topicUpdated: "تم تغيير موضوع المحادثة إلى \'{topic}\' من قِبل {participant}",
    message_text_threadPictureUpdated: "تم تغيير صورة المحادثة من قبل {participant}",
    message_text_historyClosed: "تم إغلاق محفوظات المحادثة من قبل {participant}",
    message_text_historyDisclosed: "تم الكشف عن محفوظات المحادثة من قبل {participant}",
    message_text_sentContacts: "جهات الاتصال التي تم إرسالها إلى المحادثة",
    message_text_receivedContacts: "تم تلقي جهات الاتصال من {from}",
    message_text_contactItem: "<li>{fullName} ‪({name})‬</li>",
    message_text_joiningEnabled: "تم تمكين الانضمام إلى هذه المحادثة من قبل {participant}",
    message_text_joiningDisabled: "تم تعطيل الانضمام إلى هذه المحادثة من قبل {participant}",
    message_text_legacyMemberAdded: "إن {participant} بحاجة إلى تحديث Skype للمشاركة في هذه المحادثة. يمكنك مساعدة هذا المستخدم من خلال إحالته إلى http://www.skype.com/en/download-skype/skype-for-computer/",
    message_text_legacyMemberUpgraded: "بإمكان {participant} الآن المشاركة في هذه المحادثة.",
    message_text_emptyConversation: "لا تتوفر محفوظات لهذه المحادثة",
    message_text_startedCall: "اتصال",
    message_text_startedGroupCall: "إجراء مكالمة جماعية",
    message_text_endedCall: "انتهت المكالمة",
    message_text_endedGroupCall: "انتهت المكالمة الجماعية",
    message_text_outgoingCallNoAnswer: "مكالمة، بلا رد",
    message_text_outgoingGroupCallNoAnswer: "مكالمة جماعية، بلا رد",
    message_text_missedCall: "مكالمة فائتة",
    message_text_missedGroupCall: "مكالمة جماعية فائتة",
    message_text_unknownMessageType: "نوع الرسالة غير معروف \"{mesageType}\"",
    message_text_fileTransferNotSupported: "إن تلقي الملفات عبر شبكة P2P غير مدعوم على Skype لويب",
    message_text_parsing_error: "حدث خطأ أثناء تحليل الرسالة!",
    message_text_unsupportedVideoMessageYet: "لا يتوفر دعم لتلقي رسائل الفيديو على Skype لويب",
    message_text_unsupportedAudioMessageYet: "تلقي رسائل صوتية غير معتمد على Skype for Web",
    message_text_guestRemovedBySystem: "انتهت مدة صلاحية حساب الضيف لـ {participant}",
    message_text_pollsFeatureDisabled: "عذراً، لا تتوفر الاستطلاعات في الوقت الحالي. يرجى المحاولة مرة أخرى لاحقاً. ",
    message_text_ngcUpgradeMessage_one: "تعذر على <strong>{participant}</strong> الانضمام إلى هذه المكالمة. قد يتعين عليه الاتصال بالإنترنت أو تحديث Skype أو قد يكون مستخدماً لجهاز غير مدعوم. معرفة المزيد على {link}",
    message_text_ngcUpgradeMessage_many: "تعذر على <strong>{participantList}</strong> و<strong>{lastParticipant}</strong> الانضمام إلى هذه المكالمة. قد يتعين عليهم الاتصال بالإنترنت أو تحديث Skype أو قد يكونون مستخدمين لجهاز غير مدعوم. معرفة المزيد على {link}",

    message_text_swift_card: "البطاقة",
    message_text_swift_cards: "البطاقات",
    message_text_swift_receipt: "الإيصال",
    message_text_swift_signIn: "تسجيل الدخول",
    message_text_swift_defaultTitle: "أرسل رسالة إليك",
    message_text_swift_defaultGroupTitle: "تم إرسال رسالة من قِبل {displayName}",
    message_text_swift_vat: "ضريبة القيمة المضافة",
    message_text_swift_tax: "الضريبة",
    message_text_swift_totalPrice: "المجموع",
    message_text_swift_unsupported: "عذراً! لا يمكننا إظهار هذه البطاقة على إصدار Skype الذي تستخدمه.",
    message_text_swift_unsupported_button: "التالي",
    message_text_swift_showImageTitle: "تكبير الصورة",
    message_text_swift_signInTitle: "الاتصال",
    message_text_swift_prevCard: "إظهار السابق",
    message_text_swift_nextCard: "إظهار التالي",
    message_text_swift_showAll: "إظهار الكل",
    message_text_swift_showLess: "إظهار أقل",

    swift_videocard_control_button_mute: "كتم صوت",
    swift_videocard_control_button_unmute: "إلغاء كتم الصوت",

    accessibility_swift_openUrl: "انقر لفتح موقع ويب في المستعرض",
    accessibility_swift_imBack: "انقر لإرسال رد إلى الحساب الآلي",
    accessibility_swift_call: "انقر لإجراء مكالمة",
    accessibility_swift_showImage: "انقر لتكبير الصورة",
    accessibility_swift_action_prefix: "انقر من أجل {swiftAction}",

    message_text_pluginFree_windowsUpdate_line1: "يمكنك التحديث إلى آخر إصدار من Windows 10 للاستمتاع بالمكالمات الفورية في Microsoft Edge‏ {update_link}.",
    message_text_pluginFree_windowsUpdate_line2: "كحل بديل، يمكنك تثبيت المكوّن الإضافي لـ Skype لويب إذا لم تفعل ذلك بعد.",
    message_text_pluginFree_screenSharingFallback_line1: "ستتوفر ميزة مشاركة الشاشة قريباً.",
    message_text_pluginFree_screenSharingFallback_line2: "كحل بديل، انتقل إلى تطبيق Skype ليتمكن جهازك من تلقي مشاركة الشاشة {upgrade_link}.",
    message_text_pluginFree_microphoneAccess_edge: "لم يتم الكشف عن وجود أي ميكروفون. يجب توصيل ميكروفون أو التحقق من إعدادات خصوصية الميكروفون في \"إعدادات\" -> \"الخصوصية\" -> \"الميكروفون\".",
    message_text_pluginFree_microphoneAccess_others: "لم يتم الكشف عن أي ميكروفون. يجب توصيل ميكروفون أو التحقق من إعدادات خصوصية الميكروفون لجهازك والمستعرض.",
    message_text_pluginFree_outgoingP2P_line1: "تستخدم جهة الاتصال التي تحاول الاتصال بها إصداراً قديماً من Skype. أرسل إليها هذا الارتباط لتحديث Skype‏ {upgrade_link}.",
    message_text_pluginFree_outgoingP2P_line2: "كحل بديل، ما زال بإمكانك الاتصال بها عبر تثبيت المكوّن الإضافي لـ Skype لويب أولاً.",
    message_text_pluginFree_outgoingP2P_line3: "بدلاً من ذلك، يمكنك الاتصال بها عبر الانتقال إلى استخدام تطبيق Skype لجهازك {upgrade_link}.",
    message_text_pluginFree_incomingP2P_line1: "تحاول جهة اتصال تستخدم إصداراً قديماً من Skype التواصل معك. أرسل إليها هذا الارتباط لتحديث Skype‏ {upgrade_link}.",
    message_text_pluginFree_incomingP2P_line2: "كحل بديل، يمكنك تلقي مكالمتها عبر تثبيت المكوّن الإضافي لـ Skype لويب أولاً.",
    message_text_pluginFree_incomingP2P_line3: "بدلاً من ذلك، يمكنك تلقي المكالمات منها عبر الانتقال إلى استخدام تطبيق Skype لجهازك {upgrade_link}.",
    message_text_pluginFree_incomingP2P_line4: "حاول هذا الشخص الاتصال بك ولكن حدثت مشكلة أثناء الاتصال بالمكالمة. حاول الاتصال به مرة أخرى.",
    message_text_pluginFree_noVideoCapability: "عذراً لكن لا يتوفر دعم الفيديو بعد لهذا النظام الأساسي.",

    message_text_suggestedContactGreeting: "إن <strong>{displayName}</strong> عبارة عن جهة اتصال من دفتر عناوين، ولكنها بحاجة إلى أن تكون متصلاً أولاً قبل الدردشة",
    message_text_suggestedContactConnectAction: "الاتصال على Skype",
    message_text_contactBlockedMessage: "لقد حظرت <strong>{displayName}</strong>",
    message_text_contactAccepted: "تم قبول جهة الاتصال",
    message_text_addingContactRequest: "يرغب <strong>{id}</strong> في إضافتك كجهة اتصال",
    message_text_isNowAContact: "أصبح <strong>{id}</strong> جهة اتصال الآن",
    message_text_contactRequestGreeting: "مرحباً يا {displayName}، أرغب في إضافتك كجهة اتصال.",
    message_text_contactRequestIsNowContact: "أصبح <strong>{displayName}</strong> جهة اتصال الآن",
    message_text_contactRequestOutgoingMessage: "ليس <strong>{displayName}</strong> من جهات الاتصال الخاصة بك",
    message_text_contactRequestOutgoingResendMessage: "تم إرسال طلب جهة الاتصال",
    message_text_contactRequestOutgoingResendAction: "إعادة إرسال طلب جهة الاتصال",
    message_text_contactRequestIncomingMessage: "يرغب <strong>{displayName}</strong> في إضافتك كجهة اتصال",
    message_text_contactRequestSendAction: "إضافة إلى جهات الاتصال",
    message_text_contactRequestAcceptAction: "قبول",
    message_text_contactRequestDeclineAction: "رفض",
    message_text_unblockContact: "إلغاء الحظر",
    message_text_timeStampMessage: "تم الإرسال في: ",
    message_text_longTimeStamp: "{date} عند الساعة {time}",
    message_text_removed: "تمت الإزالة في {date} عند الساعة {time}",

    message_text_presenceAvailable: "متوفر",
    message_text_presenceOnline: "متصل",
    message_text_presenceNotAvailable: "غير متوفر",
    message_text_presenceOffline: "غير متصل",
    message_text_presenceHidden: "غير مرئي",
    message_text_contactTitleLocal: "أشخاص",
    message_text_contactTitleDirectory: "الدليل",
    message_text_contactBlocked: "محظور",

    button_translations_see_original_message: "عرض الرسالة الأصلية",
    button_translations_see_translated_message: "عرض الترجمة",
    button_translator_translatorSettings: "Skype Translator",
    label_translator_translatorSettings: "معاينة Translator",
    button_translator_translatorSettingsOn: "قيد التشغيل",
    button_translator_translatorSettingsOff: "توقف عن التشغيل",
    label_translator_translatorOn: "قيد التشغيل",
    label_translator_translatorOff: "متوقف عن التشغيل",

    label_translator_selected_theirLanguage: "تم تحديد {language} لـ {name}",
    label_translator_selected_myLanguage: "حددت {language} لك",

    button_text_searchDirectory: "البحث في دليل Skype",
    message_text_emptySearchResults: "لم يتم العثور على نتائج",

    message_text_groupSearchResultsTitle: "المجموعات",
    message_title_allContacts: "كل جهات الاتصال",
    message_bucketName_other: "#",
    message_not_delivered_text: "لم يتم تسليم هذه الرسالة",
    message_edited_text: "تم تحرير هذه الرسالة",
    message_more_search_results_available: "ثمة نتائج كثيرة؛ حاول تحسين البحث",

    label_text_newConv: "جديد",

    newbee_text_header: "بدء المحادثة",
    newbee_text_cta: "ابحث عن أصدقائك عن طريق إدخال أسمائهم أو عناوين بريدهم الإلكتروني في الحقل \"بحث في Skype\".",
    newbee_text_cta_4b: "ابحث عن زملائك في العمل عبر إدخال أسمائهم في الحقل \"بحث\".",

    contactPage_text_menuLink: "جهات الاتصال",
    contactPage_text_header: "جهات الاتصال",
    contactPage_text_tab_allContacts: "كل جهات الاتصال",
    contactPage_text_tab_available: "متصل",
    contactPage_text_tab_work: "العمل",
    contactPage_text_tab_agents: "روبوتات",
    contactPage_text_hint_search: "تلميح: يمكنك إضافة جهات اتصال جديدة من خلال البحث",
    contactPage_text_manage_contacts_button: "إدارة جهات الاتصال",
    contactPage_text_informational_message: "احصل على تطبيق Skype for Business لمكالمات الفيديو والاجتماعات عبر الإنترنت.",

    settings_page_text_header: "إعدادات",
    settings_pane_opened: "تم فتح جزء الإعدادات",

    settings_im_settings_category_title: "إعدادات المراسلات الفورية",     //as in "group of Messaging settings"
    settings_privacy_category_title: "الخصوصية",
    settings_unlisted_category_title: "غير مدرجة",
    settings_contacts_category_title: "جهات الاتصال",
    settings_about_category_title: "حول",
    settings_personalization_category_title: "إضفاء طابع شخصي",
    settings_im_appearance_category_title: "مظهر المراسلات الفورية",
    settings_notifications_category_title: "الإعلامات",
    settings_unknownOption_title: "خيار غير معروف: {id}",
    settings_unknownOption_alt_text: "خيار غير معروف: {id}",

    //ATTN de-de and similar: please insert soft hypens (U+00AD) if a single "word" is more than 20 letters long.
    settings_mentionsEnabled_title: "إعلامات الإشارة باستخدام @",      //As in mention someone by typing his user name with the @ character prefix.

    // "username" in "(@&lt;username&gt;)" is a placeholder. For example, to mention an user named john2016 you type "@john2016"
    // ATTN RTL languages: The (@&lt;username&gt;) must be LTR embedded (U+202a and U+202c) so the non-alphabetic symbols are rendered in the correct order
    settings_mentionsEnabled_alt_text: "إعلامي دائماً عندما يشير إليّ أحدهم على Skype‏. (‎@&lt;username&gt;‎)",
    settings_youtube_player_title: "مشغّل YouTube",
    settings_youtube_player_alt_text: "استخدام مشغّل YouTube مباشرةً لمعاينة مقاطع الفيديو التي أرسلها أو أتلقاها.",
    settings_urlPreview_title: "معاينات ارتباطات ويب",
    settings_urlPreview_alt_text: "إظهار معاينة لمواقع ويب التي أرسلها أو أتلقاها على Skype.",
    settings_filePaste_title: "تمكين لصق الصور",
    settings_filePaste_alt_text: "تمكين لصق الصور من الحافظة مباشرةً في الدردشة",

    settings_skypeCallPolicy_title: "السماح بتلقي مكالمات من:",
    settings_skypeVideoPolicy_title: "السماح بالفيديو ومشاركة الشاشة مع:",

    settings_camera_title: "كاميرا",
    settings_microphone_title: "الميكروفون",
    settings_speaker_title: "السماعة",
    settings_no_camera_title: "لا تتوفر كاميرا",
    settings_no_microphone_title: "لا يتوفر ميكروفون",
    settings_no_speaker_title: "لا تتوفر سماعات",
    settings_close_title: "إغلاق",

    settings_default_device_name: "تحديد تلقائي",

    settings_typingIndicator_title: "مؤشر الكتابة",
    settings_typingIndicator_alt_text: "إظهار أثناء قيامي بالكتابة",

    settings_pinRecentFavorites_title: "إظهار المفضلة أعلى المحادثات الأخيرة",
    settings_pinRecentFavorites_alt_text: "قم بتثبيت المحادثات وجهات الاتصال المفضلة في أعلى قائمة الرسائل الأخيرة",

    settings_emoticonSuggestions_title: "اقتراحات رموز المشاعر",
    settings_emoticonSuggestions_alt_text: "إظهار اقتراحات رموز المشاعر أثناء كتابتي لرسائل الدردشة.",

    //Emoticons
    settings_showEmoticons_title: "إظهار رموز المشاعر",
    settings_showEmoticons_alt_text: "إظهار رموز مشاعر Skype في دردشة.",
    settings_showAnimatedEmoticons_title: "إظهار الرموز التعبيرية المتحركة",
    settings_showAnimatedEmoticons_alt_text: "إظهار حركة رموز مشاعر Skype في دردشة.",
    settings_showLargeEmoticons_title: "إظهار رموز تعبيرية كبيرة",
    settings_showLargeEmoticons_alt_text: "اجعل الرموز المشاعر الفردية أكبر في الدردشة.",

    settings_translator_title: "Translator",
    settings_translator_title_alt_text: "تمكين Skype Translator",

    settings_sendReadReceipts_title: "إرسال إيصالات بالقراءة",
    settings_sendReadReceipts_alt_text: "إظهار عندما يقرأ أشخاص آخرون رسائلك. عندما تكون هذه الميزة متوقفة عن التشغيل، سيتعذر عليك أيضاً عرض إيصالات القراءة التابعة لهم.",

    settings_privacy_opt_1_title: "أي شخص",             //as in "<Allow calls from> anyone"
    settings_privacy_opt_2_title: "جهات الاتصال فقط",      //as in "<Allow calls from> my contacts only"
    settings_privacy_opt_3_title: "لا أحد",             //as in "<Allow calls from> nobody"

    settings_short_circuit_my_contact_list: "قائمة جهات الاتصال الخاصة بي",
    settings_short_circuit_title: "إضافة الأصدقاء تلقائياً",
    settings_short_circuit_description: "سيتحقق Skype من دفاتر عناوينك وسيضيف تلقائياً الأشخاص الذين تعرفهم إلى قائمة جهات الاتصال في Skype.",
    settings_short_circuit_deny: "عدم إضافة الأصدقاء تلقائياً",
    settings_short_circuit_deny_title: "سيتعين عليك البحث عن جهات اتصال جديدة وإضافتها يدوياً.",
    settings_short_circuit_manage_contacts: "إدارة دفاتر العناوين",
    settings_short_circuit_auto_buddy_discovery_title: "كيفية عثور الأشخاص علي:",
    settings_short_circuit_auto_buddy_discovery_description: "يمكن استخدام تفاصيل الاتصال هذه للعثور عليك في Skype",
    settings_short_circuit_remove: "إزالة",
    settings_short_circuit_remove_accessible_text: "إزالة {proof}",
    settings_short_circuit_add_number: "إضافة رقم جديد",

    settings_notifications_title: "إعلامات الدردشة",
    settings_notifications_alt_text: "تلقي إعلامات لرسائل الدردشة الجديدة",
    settings_notifications_sound_title: "صوت",
    settings_notifications_sound_alt_text: "تشغيل أصوات الإعلامات أو إيقاف تشغيلها",

    settings_chat_notifications_sound_title: "أصوات الإعلام بالمحادثات",
    settings_chat_notifications_sound_alt_text: "تشغيل أصوات الإعلام لرسائل المحادثة الجديدة",
    settings_call_notifications_title: "إعلام بالمكالمات الواردة",
    settings_call_notifications_alt_text: "تلقي إعلامات بالمكالمات الواردة",
    settings_call_notifications_sound_title: "أصوات المكالمات الواردة",
    settings_call_notifications_sound_alt_text: "كتم أصوات المكالمات الواردة لفترة زمنية معينة",
    settings_call_notifications_sound_defer_for_few: "كتم الصوت لمدة 4 ساعات ({untilTime})",
    settings_call_notifications_sound_defer_for_many: "كتم الصوت لمدة 8 ساعات ({untilTime})",
    settings_call_notifications_sound_defer_for_until: "كتم حتى أقوم بالتشغيل مرة أخرى",

    // Ringing deferrer:
    settings_ringing_deferrer_title: "كتم صوت الرنين",
    settings_ringing_deferrer_alt_text: "كتم أصوات رنين المكالمات الواردة لفترة زمنية معينة",
    settings_ringing_deferrer_defer_for: "لمدة ساعة {count}", // as in "mute the ringing for {count} hours"
    settings_ringing_deferrer_defer_for_few: "لمدة ساعتين {count}",
    settings_ringing_deferrer_defer_for_many: "لمدة {count} ساعة",

    settings_dark_theme: "نسق داكن",
    settings_dark_theme_alt_text: "تغيير ألوان هذا التطبيق.",
    settings_video_autoplay: "تشغيل الفيديو تلقائياً",
    settings_video_autoplay_alt_text: "اختر وقت تشغيل مقاطع الفيديو تلقائياً.",

    setting_on: "تشغيل",
    setting_off: "إيقاف تشغيل",

    search_skype_for_friends_and_family_header: "البحث عن أصدقاء على Skype",
    search_skype_for_friends_and_family_message: "أدخل اسم Skype أو البريد الإلكتروني أو الرقم.",
    search_skype_for_friends_and_family_tip: "تلميح: يمكنك تضييق نطاق البحث بتضمين المدينة أو البلد أو المنطقة.",
    search_skype_for_friends_and_family_text: "إنها طريقة سهلة ورائعة للتواصل.",
    search_skype_for_friends_and_family_link: "اكتشف المزيد هنا.",
    search_skype_for_friends_and_family_searchDirectory: "بحث في الدليل",

    short_circuit_contacts_page_message: "إضافة الأشخاص بسرعة من دفتر عناوينك",
    short_circuit_contacts_page_message_v2: "أضف الأصدقاء تلقائياً من دفتر عناوينك",
    short_circuit_contacts_page_cta: "إضافة أصدقاء",

    about_app_version: "إصدار التطبيق",
    about_assets_version: "إصدار الأصول المرئية",
    about_plugin_version: "إصدار المكوّن الإضافي",
    about_plugin_not_available: "غير متوفر",
    about_faq: "الأسئلة المتداولة",

    message_text_callingNotSupportedBrowser: "مكالمات الصوت والفيديو غير معتمدة على المتصفح الخاص بك",
    message_text_callingNotSupportedOS: "مكالمات الصوت والفيديو غير معتمدة على نظام التشغيل لديك",
    message_text_callingIsDisabled: "المكالمات معطلة في الوقت الحالي.",

    chatLogmenuItem_text_copy: "نسخ كاقتباس",
    chatLogmenuItem_text_quote: "اقتباس الرسالة",
    chatLogmenuItem_text_edit: "تحرير الرسالة",
    chatLogmenuItem_text_remove: "إزالة الرسالة",
    chatLogmenuItem_text_like: "تسجيل الإعجاب بالرسالة",
    chatLogmenuItem_text_save: "حفظ",
    chatLogmenuItem_copy_link: "نسخ الارتباط",
    chatLogmenuItem_open_link: "فتح",
    chatLogmenuItem_text_copySelection: "نسخ كاقتباس",
    chatLogmenuItem_text_copyText: "نسخ النص",
    chatLogIntroText_text: "يمكنك الدردشة مع الأشخاص الذين يحررون هذا الملف في Office Online‏. | لن يتم حفظ هذه الدردشة عند إغلاق الملف.",

    recentItemMenuItem_text_leave: "مغادرة المحادثة",
    recentItemMenuItem_text_remove: "حذف المحادثة",
    recentItemMenuItem_text_remove_4b: "إغلاق المحادثة",
    recentItemMenuItem_text_markRead: "وضع علامة كمقروء",
    recentItemMenuItem_text_markAllConversationsRead: "وضع علامة كمقروءة للكل",
    recentItemMenuItem_text_muteConversation: "إيقاف تشغيل الإعلامات",
    recentItemMenuItem_text_unmuteConversation: "تشغيل الإعلامات",

    actionsMenuItem_text_addParticipants: "إضافة مشاركين",
    actionsMenuItem_text_scheduleCall: "جدولة مكالمة",

    typingIndicator_label_oneParticipant: "تتم الكتابة الآن من قبل {firstParticipantName}...",
    typingIndicator_label_twoParticipants: "تتم الآن الكتابة من قبل {firstParticipantName} و{secondParticipantName}...",
    typingIndicator_label_multipleParticipants: "{firstParticipantName} و{secondParticipantName} و{count} من الأشخاص الآخرين يكتبون...",
    typingIndicator_label_multipleParticipants_few: "تتم الآن الكتابة من قبل {firstParticipantName} و{secondParticipantName} و{count} من الأشخاص الآخرين...",
    typingIndicator_label_multipleParticipants_many: "تتم الآن الكتابة من قِبل {firstParticipantName} و{secondParticipantName} و{count} من الأشخاص الآخرين...",

    button_text_emoticons: "رموز المشاعر",
    button_title_emoticons: "رموز المشاعر",
    button_text_videoCall: "مكالمة فيديو",
    button_text_audioCall: "إجراء مكالمة صوتية",
    button_text_joinCall: "الانضمام إلى المكالمة",
    button_text_joinCallWithVideo: "الانضمام إلى مكالمة فيديو",
    button_text_addParticipants: "إضافة",
    button_text_cancelAddParticipants: "إلغاء",
    button_text_createConversation: "إنشاء",
    button_text_filePicker: "مشاركة صورة",
    button_text_chatInputActionPicker: "إرسال الملفات والوسائط",
    button_text_poll: "إرسال استطلاع",
    button_text_moreActions: "المزيد من الإجراءات",
    button_text_closeSettings: "إغلاق",

    callScreen_text_terminationPrompt: "أنت في مكالمة الآن، هل تريد بالتأكيد قطع المكالمة وإغلاق Skype؟",
    callscreen_text_terminationMessage: "انتهت المكالمة",
    callscreen_text_autoCallConnectingMessage: "بانتظار انضمام الآخرين...",
    callscreen_text_autoCallTimeoutMessage: "يبدو أنك وحدك هنا، حاول الانضمام إلى المكالمة مرة أخرى لاحقاً",
    callscreen_text_autoCallFailedMessage: "يتعذر إعداد مكالمة، يرجى المحاولة مرة أخرى لاحقاً",
    callscreen_text_statusMessageConnecting: "جارٍ الاتصال...",
    callscreen_text_statusMessageScreenReaderConnecting: "جارٍ الاتصال بـ {contactName}",
    callscreen_text_statusMessageScreenReaderEnding_less_than_minute: "انتهت المكالمة، مدة المكالمة أقل من دقيقة واحدة",
    callscreen_text_statusMessageScreenReaderEnding_minutes: "انتهت المكالمة، مدة المكالمة {count} دقيقة",
    callscreen_text_statusMessageScreenReaderEnding_minutes_few: "انتهت المكالمة، مدة المكالمة {count} من الدقائق",
    callscreen_text_statusMessageScreenReaderEnding_minutes_many: "انتهت المكالمة، مدة المكالمة {count} من الدقائق",
    callscreen_text_participant_joined_notification: "انضم {name}",
    callscreen_text_participant_left_notification: "غادر {name}",
    callscreen_text_participant_screen_shared_notification: "بدأت مشاركة الشاشة لدى {name}",
    callscreen_text_participant_screen_unshared_notification: "توقفت مشاركة الشاشة لدى {name}",
    callscreen_text_statusMessageCalling: "جارٍ الطلب...",
    callscreen_text_enterFullscreen: "الدخول في وضع ملء الشاشة",
    callscreen_text_exitFullscreen: "الخروج من وضع ملء الشاشة",
    callscreen_text_enterGvcGrid: "وضع الشبكة",
    callscreen_text_videoOn: "تشغيل الفيديو",
    callscreen_text_videoOff: "إيقاف تشغيل الفيديو",
    callscreen_text_plusButton: "إضافة مشاركين، مشاركة الشاشات وغيرها",
    callscreen_text_shareScreens: "مشاركة الشاشات...",
    callscreen_text_shareScreen: "مشاركة الشاشة",
    callscreen_text_stopSharingScreen: "إيقاف المشاركة",
    callscreen_text_addParticipants: "إضافة أشخاص إلى هذه المكالمة",
    callscreen_text_microphoneOn: "تشغيل الميكروفون",
    callscreen_text_microphoneOff: "إيقاف تشغيل الميكروفون",
    callscreen_text_endCall: "إنهاء المكالمة",
    callscreen_text_participants: "{count} في المكالمة",
    callscreen_text_showChat: "إظهار الرسائل الفورية",
    callscreen_text_showContacts: "إظهار جهات الاتصال",
    callscreen_text_hangUp: "إنهاء المكالمة",
    callscreen_text_addParticipantsToCall: "إضافة أشخاص إلى هذه المكالمة",
    callScreen_text_andMore: "وغير ذلك",
    callscreen_text_dialpadOn: "تشغيل لوحة الطلب",
    callscreen_text_dialpadOff: "إيقاف تشغيل لوحة الطلب",
    callscreen_title_zoom: "انقر نقراً مزدوجاً للتكبير/التصغير",
    callscreen_text_showAVSettings: "إعدادات الصوت والفيديو",
    callscreen_text_transferCall: "تحويل المكالمة",
    callscreen_text_showSidebar: "إظهار الشريط الجانبي",
    callscreen_text_hideSidebar: "إخفاء الشريط الجانبي",
    callscreen_participantMenu_pin: "يثبت",
    callscreen_participantMenu_unpin: "إلغاء التثبيت",
    callscreen_participantMenu_zoomIn: "تكبير",
    callscreen_participantMenu_zoomOut: "تصغير",
    callscreen_participantMenu_chat: "دردشة",

    toast_incoming_text_title: "مكالمة واردة",
    toast_incoming_text_acceptWithVideo: "قبول مع الفيديو",
    toast_incoming_text_acceptWithAudio: "قبول مع الصوت",
    toast_incoming_text_reject: "رفض المكالمة",
    toast_install_text_title: "يحاول الاتصال بك",
    toast_install_text_installButton: "تثبيت المكون الإضافي",
    toast_install_text_message: "ستحتاج إلى مكون إضافي لإجراء مكالمات Skype",

    pluginInstall_main_close_screen_title: "هل تريد الخروج بالتأكيد؟",
    pluginInstall_main_close_screen_subtitle: "تكاد تنتهي من إعداد مكالمات Skype.",
    pluginInstall_main_close_screen_finish_text: "إنهاء الإعداد",
    pluginInstall_main_close_screen_leave_text: "خروج",

    pluginInstall_extension_main_text_title: "يمكنك تمكين مكالمات Skype ببضع خطوات بسيطة...",
    pluginInstall_extension_main_text_subtitle: "ابدأ بتثبيت الإضافة \"مكالمات Skype\" في Chrome",
    pluginInstall_extension_main_text_add_extension: "إضافة ملحق",

    pluginInstall_extension_main_installed_text_title: "ممتاز!",
    pluginInstall_extension_main_installed_text_subtitle: "ثبّت الآن المكون الإضافي \"Skype لويب\" وتكون عملية الإعداد قد انتهت",
    pluginInstall_extension_main_installed_get_plugin_text: "الحصول على المكون الإضافي",

    pluginInstall_extension_main_install_failed_text_title: "عذراً، حدث خطأ ما",
    pluginInstall_extension_main_install_failed_text_subtitle: "فلنحاول مرة أخرى...",
    pluginInstall_extension_main_install_failed_go_to_chrome_webstore_text: "الانتقال إلى متجر Chrome على ويب",

    pluginInstall_main_text_close: "إغلاق",
    pluginInstall_main_text_title: "هل تريد إجراء مكالمة؟",
    pluginInstall_main_text_subtitle: "عليك تثبيت المكون الإضافي لإجراء مكالمات Skype",
    pluginInstall_main_text_install: "تثبيت المكون الإضافي",
    pluginInstall_steps_text_restart: "إعادة التشغيل",
    pluginInstall_steps_text_title: "فلنثبت المكون الإضافي.",
    pluginInstall_steps_text_subtitle: "اتبع ببساطة هذه الخطوات الثلاث لإعداد مكالمات Skype",
    pluginInstall_steps_text_termsAndPrivacy: "عبر تثبيت مكون Skype الإضافي، فإنك تقر بأنك قرأت ووافقت على {terms_link} و{privacy_link} التابعة لـ Skype.",
    pluginInstall_steps_text_termsLink: "شروط الاستخدام",
    pluginInstall_steps_text_privacyLink: "سياسة خصوصية Skype",
    pluginInstall_mac_chrome_text_download: "انقر فوق ملف المكون الإضافي.",
    pluginInstall_mac_chrome_text_install: "اتبع الإرشادات.",
    pluginInstall_mac_chrome_text_enjoy: "استمتع بمكالمات Skype المجانية.",
    pluginInstall_mac_chrome_text_enjoy_4b: "أجرِ مكالمات Skype.",
    pluginInstall_mac_safari_text_download: "انتقل إلى التنزيلات ثم انقر نقراً مزدوجاً فوق ملف المكون الإضافي.",
    pluginInstall_mac_safari_text_install: "اتبع الإرشادات لتثبيت المكون الإضافي.",
    pluginInstall_mac_safari_text_enjoy: "استمتع بإجراء مكالمات Skype مجانية عبر ويب.",
    pluginInstall_mac_safari_text_enjoy_4b: "أجرِ مكالمات Skype.",
    pluginInstall_mac_firefox_text_download: "افتح ملف المكون الإضافي.",
    pluginInstall_mac_firefox_text_install: "اتبع الإرشادات.",
    pluginInstall_mac_firefox_text_enjoy: "استمتع بمكالمات Skype المجانية.",
    pluginInstall_mac_firefox_text_enjoy_4b: "أجرِ مكالمات Skype.",
    pluginInstall_mac_unknown_download: "انتقل إلى التنزيلات ثم انقر نقراً مزدوجاً فوق ملف المكون الإضافي.",
    pluginInstall_mac_unknown_install: "اتبع الإرشادات لتثبيت المكون الإضافي.",
    pluginInstall_mac_unknown_enjoy: "استمتع بإجراء مكالمات Skype مجانية عبر ويب.",
    pluginInstall_windows_chrome_text_download: "انقر فوق ملف المكون الإضافي.",
    pluginInstall_windows_chrome_text_install: "انتظر ليتم تثبيت المكون الإضافي.",
    pluginInstall_windows_chrome_text_enjoy: "استمتع بمكالمات Skype المجانية.",
    pluginInstall_windows_chrome_text_enjoy_4b: "أجرِ مكالمات Skype.",
    pluginInstall_windows_msie_text_download: "انقر فوق \"تشغيل\" لبدء الاستخدام.",
    pluginInstall_windows_msie_text_install: "انتظر ليتم تثبيت المكون الإضافي.",
    pluginInstall_windows_msie_text_enjoy: "استمتع بمكالمات Skype المجانية.",
    pluginInstall_windows_msie_text_enjoy_4b: "أجرِ مكالمات Skype.",
    pluginInstall_windows_firefox_text_download: "انقر فوق \"حفظ ملف\" لبدء الاستخدام.",
    pluginInstall_windows_firefox_text_install: "انقر فوق ملف المكون الإضافي.",
    pluginInstall_windows_firefox_text_enjoy: "استمتع بمكالمات Skype المجانية.",
    pluginInstall_windows_firefox_text_enjoy_4b: "أجرِ مكالمات Skype.",
    pluginInstall_windows_unknown_text_download: "انقر فوق \"تشغيل\" لبدء الاستخدام.",
    pluginInstall_windows_unknown_text_install: "انتظر ليتم تثبيت المكون الإضافي.",
    pluginInstall_windows_unknown_text_enjoy: "استمتع بمكالمات Skype المجانية.",
    pluginInstall_windows_unknown_text_enjoy_4b: "أجرِ مكالمات Skype.",
    pluginInstall_unblock_text_title: "تمكين مكوّن Skype الإضافي",
    pluginInstall_unblock_text_chrome_subtitle: "يرجى النقر فوق أيقونة المكوّن الإضافي في شريط العنوان وتحديد \"السماح دائماً بالمكونات الإضافية على web.skype.com\" لمتابعة هذه المكالمة.",
    pluginInstall_unblock_text_firefox_subtitle: "يرجى النقر فوق أيقونة المكوّن الإضافي في شريط العنوان وتحديد \"السماح والحفظ\" لمتابعة هذه المكالمة.",
    pluginInstall_callback_text_title: "الاتصال بـ {displayName}",
    pluginInstall_callback_text_subtitle: "تم الآن تثبيت المكون الإضافي ويمكنك البدء بإجراء المكالمات الآن",
    pluginInstall_callback_text_call: "اتصال",
    pluginInstall_callback_text_accept: "قبول المكالمة",
    pluginInstall_callback_text_notNow: "ليس الآن",
    pluginInstall_label_text_start: "تثبيت المكون الإضافي - بدء",
    pluginInstall_label_text_download: "تثبيت المكون الإضافي - تنزيل",
    pluginInstall_label_text_unblock: "تثبيت المكوّن الإضافي - إلغاء حظر مكوّن Skype الإضافي",
    pluginInstall_label_text_continue: "تثبيت المكون الإضافي - متابعة المكالمة",
    pluginInstall_label_text_autoUpdateDisclaimer: "سيتم تحديث هذا المكون الإضافي لتقديم أفضل تجربة استخدام. إذا لم تكن ترغب في تطبيق التحديثات، فيرجى عدم تثبيت المكون الإضافي.",

    notification_text_osNotSupported: "مكالمة لم يُرد عليها من {callerName}. لا يدعم نظام التشغيل هذا المكالمات الصوتية ومكالمات الفيديو.",
    notification_text_browserNotSupported: "مكالمة لم يُرد عليها من {callerName}. أنت تستخدم حالياً مستعرض غير معتمد.",
    notification_text_learnMore: "معرفة المزيد",
    notification_text_hardware_camera: "تعذر العثور على كاميرا",
    notification_text_hardware_mic: "تعذر العثور على ميكروفون",
    notification_text_hardware_speaker: "تعذر العثور على سماعات",

    notification_text_group_conversation_from: "محادثة جماعية من",

    notification_text_avatar_not_supported_image_type: "إنّ نوع الصورة التي حاولت تحميلها غير معتمد",
    notification_text_avatar_too_large: "حجم الصورة التي حددتها كبير جداً، يرجى استخدام صورة ذات حجم ملف أصغر.",
    notification_text_avatar_upload_error: "تعذر تغيير صورة ملف تعريفك، يرجى المحاولة مرة أخرى.",

    enable_browser_notifications_toast: "تشغيل إعلامات سطح المكتب ليتم إعلامك بالرسائل الجديدة.",
    enable_browser_notifications_link_text: "تشغيل إعلامات سطح المكتب",

    allow_browser_notifications_header: "لا تفوّت رسالة",
    allow_browser_notifications_text: "انقر فوق \"السماح\" ليتم إعلامك بالرسائل الجديدة.",

    media_clicktoplay: "النقر للتشغيل",

    media_picturesharing_one: "مشاركة صورة",
    media_picturesharing_group: "شارك {senderName} صورة",
    media_picturesharing_label: "فتح الصورة في نافذة جديدة",

    media_voice_message: "رسالة صوتية",
    media_audiosharing_one: "شارك رسالة صوتية",
    media_audiosharing_group: "{senderName} شارك رسالة صوتية",

    media_videosharing_one: "شارك فيديو",
    media_videosharing_group: "تمت مشاركة فيديو من قِبل {senderName}",

    media_videomessage_expired: "انتهت مدة صلاحية رسالة الفيديو",
    media_audiomessage_expired: "انتهت صلاحية الرسالة الصوتية",

    mediaPlayer_play: "تشغيل",
    mediaPlayer_pause: "إيقاف مؤقت",
    videoPlayer_fullscreen: "ملء الشاشة",
    videoPlayer_exitFullscreen: "إنهاء وضع ملء الشاشة",

    action_button_confirm: "تأكيد",
    action_button_cancel: "إلغاء",
    action_button_save: "حفظ",
    action_button_block: "حظر",
    action_button_delete: "حذف",
    action_button_delete_4b: "إغلاق",
    action_button_send: "إرسال",
    action_button_share_conversation: "مشاركة المحادثة",
    action_button_leave: "خروج",

    media_mojisharing_one: "تمت مشاركة Moji",
    media_mojisharing_group: "تمت مشاركة Moji من قِبل {senderName}",
    emoticonPicker_heading_label: "اختيار رمز مشاعر",

    accessibility_recentItem_conversation_muted: "كتم صوت المحادثة.",
    accessibility_recentItem_oneToOne: "محادثة مع {topic}.‏ {muted} اضغط على Shift + F ten لمزيد من الخيارات.",
    accessibility_recentItem_oneToOne_many: "محادثة مع {topic}.‏ {muted} اضغط على Shift + F ten لمزيد من الخيارات.",
    accessibility_recentItem_oneToOne_unread: "محادثة مع {topic}،‏ {count} رسالة غير مقروءة. {muted} اضغط على Shift + F ten لمزيد من الخيارات.",
    accessibility_recentItem_oneToOne_unread_many: "محادثة مع {topic}،‏ {count} رسالة غير مقروءة. {muted} اضغط على Shift + F ten لمزيد من الخيارات.",
    accessibility_recentItem_group_unread: "محادثة جماعية مع {count} رسالة غير مقروءة {topic}.‏ {muted} اضغط على Shift + F ten لمزيد من الخيارات.",
    accessibility_recentItem_group_unread_many: "محادثة جماعية مع {count} رسالة غير مقروءة {topic}.‏ {muted} اضغط على Shift + F ten لمزيد من الخيارات.",
    accessibility_recentItem_group: "محادثة جماعية {topic}.‏ {muted} اضغط على Shift + F ten لمزيد من الخيارات.",
    accessibility_recentItem_group_many: "محادثة جماعية {topic}.‏ {muted} اضغط على Shift + F ten لمزيد من الخيارات.",
    accessibility_recentItem_recent_group: "المحادثات الأخيرة",
    accessibility_chatLog_newMessage: "رسالة جديدة من {author}‏، {content}",
    accessibility_chatLog_newMessage_withoutAuthor: "رسالة جديدة، {content}",

    accessibility_searching: "جارٍ البحث",
    accessibility_searchItem_oneToOne: "{contactName}‏، {id}‏، {status}‏، {index} من {totalResults} في \"الأشخاص\".",
    accessibility_searchItem_group: "{groupName} المجموعة، {index} من {totalResults} في \"المجموعات\".",
    accessibility_searchItem_group_displayMessage: "المجموعة {groupName}‏، {displayMessage}‏، {index}‏ من {totalResults} في \"المجموعات\".",
    accessibility_searchItem_directoryList: "{contactName}‏، {id}‏، {status}‏، {index} من {totalResults} في دليل Skype.",

    accessibility_localSearchUpdated: "تم تحديث البحث وتم العثور على {totalSearchResults} نتيجة في جهات الاتصال والمجموعات. {peopleSearchResults} في الأشخاص و{groupsSearchResults} في \"المجموعات\".",
    accessibility_localSearchUpdated_few: "تم تحديث البحث وتم العثور على {totalSearchResults} من النتائج في جهات الاتصال والمجموعات. {peopleSearchResults} في الأشخاص و{groupsSearchResults} في المجموعات.",
    accessibility_localSearchUpdated_many: "تم تحديث البحث وتم العثور على {totalSearchResults} من النتائج في جهات الاتصال والمجموعات. {peopleSearchResults} في الأشخاص و{groupsSearchResults} في المجموعات.",
    accessibility_localSearchUpdated_4b: "تم تحديث عملية البحث وتم العثور على {totalSearchResults} نتيجة في جهات اتصالك.",
    accessibility_localSearchUpdated_4b_few: "تم تحديث عملية البحث وتم العثور على {totalSearchResults} من النتائج في جهات اتصالك.",
    accessibility_localSearchUpdated_4b_many: "تم تحديث عملية البحث وتم العثور على {totalSearchResults} من النتائج في جهات اتصالك.",
    accessibility_localSearchNoResults: "تم تحديث البحث ولم يتم العثور على نتائج في جهات الاتصال والمجموعات.",
    accessibility_localSearchNoResults_4b: "تم تحديث عملية البحث ولم يتم العثور على نتائج في جهات اتصالك.",
    accessibility_searchSkypeDirectory: "اضغط على enter للبحث في دليل Skype.",
    accessibility_clearSearchField_ariaLabel: "امسح حقل إدخال البحث.",

    accessibility_skypeDirectorySearchUpdated: "تم تحديث البحث وتم العثور على {totalSearchResults} نتيجة في دليل Skype.",
    accessibility_skypeDirectorySearchUpdated_few: "تم تحديث البحث وتم العثور على {totalSearchResults} من النتائج في دليل Skype.",
    accessibility_skypeDirectorySearchUpdated_many: "تم تحديث البحث وتم العثور على {totalSearchResults} من النتائج في دليل Skype.",

    accessibility_totalSearchUpdated: "تم تحديث البحث وتم العثور على {totalSearchResults} نتيجة. {peopleSearchResults} في الأشخاص و{groupsSearchResults} في المجموعات و{SkypeDirectorySearchResults} في دليل Skype.",
    accessibility_totalSearchUpdated_few: "تم تحديث البحث وتم العثور على {totalSearchResults} من النتائج. {peopleSearchResults} في الأشخاص و{groupsSearchResults} في المجموعات و{SkypeDirectorySearchResults} في دليل Skype.",
    accessibility_totalSearchUpdated_many: "تم تحديث البحث وتم العثور على {totalSearchResults} من النتائج. {peopleSearchResults} في الأشخاص و{groupsSearchResults} في المجموعات و{SkypeDirectorySearchResults} في دليل Skype.",
    accessibility_totalSearchNoResults: "تم تحديث البحث ولم يتم العثور على نتائج في جهات الاتصال ولا في المجموعات ولا في دليل Skype.",

    accessibility_contactProfile_headingWithClosedProfile: "افتح ملف {topic} التعريفي.",
    accessibility_contactProfile_openedProfile: "تم فتح ملف تعريف {topic}.",
    accessibility_contactProfile_closedProfile: "تم إغلاق ملف تعريف {topic}.",
    accessibility_contactProfile_headingWithOpenedProfile: "أغلق ملف {topic} التعريفي.",

    accessibility_groupProfile_headingWithClosedProfile: "افتح ملف تعريف المجموعة.",
    accessibility_groupProfile_headingWithOpenedProfile: "أغلق ملف تعريف المجموعة.",
    accessibility_groupProfile_attendeeMenu: "{participantName}. خيارات إضافية.",
    accessibility_groupProfile_adminMenu: "{participantName}، مسؤول. خيارات إضافية.",
    accessibility_groupProfile_guestMenu: "{{participantName}، ضيف. خيارات إضافية.",
    accessibility_groupProfile_historyToggle_on: "توفير محفوظات الدردشة للشخص الذي انضم حديثاً. قيد التشغيل.",
    accessibility_groupProfile_historyToggle_off: "توفير محفوظات الدردشة للشخص الذي انضم حديثاً. متوقف عن التشغيل.",
    accessibility_groupProfile_joiningToggle_on: "السماح للأشخاص بالانضمام إلى هذه المجموعة عبر ارتباط. قيد التشغيل.",
    accessibility_groupProfile_joiningToggle_off: "السماح للأشخاص بالانضمام إلى هذه المجموعة عبر ارتباط. متوقف عن التشغيل.",

    accessibility_me_expandProfile: "توسيع ملف التعريف",
    accessibility_me_collapseProfile: "طي ملف التعريف",
    accessibility_me_availabilityOnAriaLabel: "تم تعيين حالة الحضور عبر الإنترنت إلى متصل (الإعلامات قيد التشغيل)",
    accessibility_me_availabilityOffAriaLabel: "تم تعيين حالة الحضور عبر الإنترنت إلى غير مرئي (الإعلامات متوقفة عن التشغيل)",

    accessibility_contactPickerUpdated: "تم تحديث عملية البحث وتم العثور على {totalSearchResults} نتيجة في جهات اتصالك.",
    accessibility_contactPickerUpdated_few: "تم تحديث عملية البحث وتم العثور على {totalSearchResults} من النتائج في جهات اتصالك.",
    accessibility_contactPickerUpdated_many: "تم تحديث عملية البحث وتم العثور على {totalSearchResults} من النتائج في جهات اتصالك.",
    accessibility_contactPickerNoResults: "تم تحديث عملية البحث ولم يتم العثور على نتائج في جهات اتصالك.",
    accessibility_contactPickerResultRemoved: "تمت إزالة {displayName} من قائمة مشاركي المحادثة الجديدة",

    accessibility_contact_blocked_success: "تم حظر جهة الاتصال",
    accessibility_contact_blocked_failure: "تعذر حظر جهة الاتصال",
    accessibility_contact_unblocked_success: "تم إلغاء حظر جهة الاتصال",
    accessibility_contact_unblocked_failure: "فشل إلغاء حظر جهة الاتصال",
    accessibility_contact_request_sent_success: "تم إرسال طلب جهة الاتصال",
    accessibility_contact_request_sent_failure: "فشل إرسال طلب جهة الاتصال",
    accessibility_contact_request_accepted_success: "تم قبول طلب جهة الاتصال",
    accessibility_contact_request_accepted_failure: "فشل قبول طلب جهة الاتصال",
    accessibility_contact_request_declined_success: "تم رفض طلب جهة الاتصال",
    accessibility_contact_request_declined_failure: "فشل رفض طلب جهة الاتصال",
    accessibility_contact_sent: "تم إرسال جهة الاتصال",
    accessibility_contact_deleted_success: "تم حذف جهة الاتصال",
    accessibility_contact_deleted_failure: "تعذر حذف جهة الاتصال",
    accessibility_contact_add_favorite_success: "تمت إضافة جهة الاتصال إلى المفضلة",
    accessibility_contact_add_favorite_failure: "فشل إضافة جهة الاتصال إلى المفضلة",
    accessibility_contact_remove_favorite_success: "تمت إزالة جهة الاتصال من المفضلة",
    accessibility_contact_remove_favorite_failure: "فشل إزالة جهة الاتصال من المفضلة",

    accessibility_selectBox_expanded: "مربع تحرير وسرد موسع",
    accessibility_selectBox_collapsed: "مربع تحرير وسرد مطوي",

    accessibility_addPeopleToConversation_ariaLabel: "إضافة أشخاص إلى هذه المحادثة",
    addPeopleToConversation_tooltip: "إضافة أشخاص",
    accessibility_startVideoCall_ariaLabel: "إجراء مكالمة فيديو",
    startVideoCall_tooltip: "إجراء مكالمة فيديو",
    accessibility_startCall_ariaLabel: "اتصال",
    videoCallDisabled_tooltip: "لا يمكنك إجراء مكالمات فيديو مع {agentName}",
    startCall_tooltip: "اتصال",
    accessibility_startGroupCall_ariaLabel: "الاتصال بالمجموعة",
    callDisabled_tooltip: "لا يمكنك إجراء مكالمات مع {agentName}",
    startGroupCall_tooltip: "الاتصال بالمجموعة",
    turnOffChatNotifications_tooltip: "إيقاف تشغيل إعلامات الدردشات",
    turnOnChatNotifications_tooltip: "تشغيل إعلامات الدردشات",
    giveFeedback_tooltip: "إعطاء ملاحظات",
    giveFeedback_subject: "ملاحظات لـ Skype على ويب",
    giveFeedback_body: "إذا كنت تواجه مشكلةً أو لديك ملاحظات تريد مشاركتها مع فريق Skype، يرجى إعلامنا بها أدناه.",
    giveFeedback_button_label: "ملاحظات",

    conversationHeader_heading_ariaLabel: "محادثة موضوعها {topic}.",
    groupProfile_spacesLink_ariaLabel: "ارتباط إلى دردشة المجموعة: {spacesUrl}",

    conversation_header_topic_default: "بلا عنوان",
    conversation_header_topic_untitled_conversation: "محادثة بلا عنوان",
    conversation_header_topic_people_chatting: "{count} من الأشخاص متوفرون",
    conversation_header_topic_people_chatting_few: "{count} من الأشخاص متوفرون",
    conversation_header_topic_people_chatting_many: "{count} من الأشخاص متوفرون",

    message_text_presenceActive: "نشط",
    message_text_presenceMobile: "على الجوال",
    message_text_presenceAway: "بالخارج",
    message_text_presenceBusy: "مشغول",
    message_text_presenceDoNotDisturb: "ممنوع الإزعاج",
    message_text_presenceUnknown: "الحالة غير معروفة",

    message_text_activity_inAMeeting: "في اجتماع",
    message_text_activity_urgentInterruptionsOnly: "المقاطعات الطارئة فقط",
    message_text_activity_onThePhone: "في مكالمة عبر الهاتف",
    message_text_activity_inAConference: "في مؤتمر",
    message_text_activity_offWork: "خارج العمل",
    message_text_activity_outOfOffice: "خارج المكتب",
    message_text_activity_presenting: "تقديم",

    expressionPicker_prevPage: "علامات التبويب السابقة",
    expressionPicker_nextPage: "علامات التبويب التالية",
    expressionPicker_selected_item_title: "تم تحديد {itemTitle}.",
    expressionPicker_mruTab_title: "مستخدمة مؤخراً",
    expressionPicker_mruTab_ariaLabel: "مستخدمة مؤخراً",
    expressionPicker_mruTab_emptyText: "ستظهر العناصر التي تم استخدامها مؤخراً هنا.",
    expressionPicker_tab_emptyText: "علامة التبويب هذه فارغة",
    expressionPicker_bingTab_title: "Bing",
    expressionPicker_bingTab_ariaLabel: "بحث بواسطة Bing عن صور",
    expressionPicker_bingTab_emptyText: "تظهر نتائج Bing هنا",
    expressionPicker_bingTab_loadingText: "يتم الآن التحميل...",
    expressionPicker_bingTab_errorText: "حدث خطأ ما! يرجى المحاولة مرة أخرى لاحقاً",
    expressionPicker_bingPack_title: "نتائج بحث Bing",
    expressionPicker_bingPack_ariaLabel: "نتائج بحث Bing",
    expressionPicker_bingGifsPack_title: "صور بتنسيق Gif شائعة من Bing",
    expressionPicker_bingMemePack_title: "أشكال إيمائية شائعة من Bing",
    expressionPicker_bingGifsPack_ariaLabel: "صور بتنسيق Gif شائعة من Bing",
    expressionPicker_bingMemePack_ariaLabel: "أشكال إيمائية شائعة من Bing",

    expressionPicker_giphyImgTab_title: "بحث في Giphy",
    expressionPicker_giphyImgTab_ariaLabel: "بحث عن صور متحركة بتنسيق GIF. تشغيل بواسطة Giphy",
    expressionPicker_giphyImgTab_emptyText: "تظهر نتائج Giphy هنا",
    expressionPicker_giphyImgTab_loadingText: "يتم الآن التحميل...",
    expressionPicker_giphyImgTab_errorText: "حدث خطأ ما! يرجى المحاولة مرة أخرى لاحقاً",
    expressionPicker_giphyImgTab_terms: "شروط الاستخدام",
    expressionPicker_giphyImgPack_title: "نتائج بحث Giphy",
    expressionPicker_giphyImgPack_ariaLabel: "نتائج بحث Giphy",

    input_placeholder_searchPESItems: "البحث عن عناصر...",
    input_searchPESItems_ariaLabel: "البحث عن عناصر. كتابة كلمة أساسية",
    expressionPicker_localSearchTab_title: "بحث",
    expressionPicker_localSearchTab_emptyText: "البحث عن رموز المشاعر وMojis",
    expressionPicker_localSearchPack_title: "اقتراحات سريعة",
    expressionPicker_localSearchPack_ariaLabel: "اقتراحات سريعة",

    expressionPicker_mruEmoticonPack_title: "رموز المشاعر",
    expressionPicker_mruEmoticonPack_ariaLabel: "رموز المشاعر",
    expressionPicker_mruMojiPack_title: "Mojis",
    expressionPicker_mruMojiPack_ariaLabel: "Mojis",
    expressionPicker_store_title: "متجر التعابير من Skype",
    expressionPicker_store_free: "مجاني",
    expressionPicker_storeTab_title: "المتجر",
    expressionPicker_store_Downloaded: "تم التنزيل",
    expressionPicker_store_Downloading: "جارٍ التنزيل...",
    expressionPicker_store_removeTab: "إزالة",
    input_placeholder_searchPESStore: "بحث",
    accessibility_open_picker: "تم توسيع القائمة",
    accessibility_close_picker: "تم طي القائمة",

    pes_moji_error_text: "تعذر تحميل Moji! يرجى المحاولة مرة أخرى لاحقاً",

    // Skype Polls feature related strings
    poll_designer_question_placeholder: "طرح سؤال...",
    poll_designer_answer_placeholder: "إضافة خيار...",
    poll_message_question_header: "الاستطلاع: {pollQuestion}",
    poll_message_goto_text: "انتقل إلى {fallbackLink} للتصويت.",
    poll_message_people_voted: "{count} من الأشخاص صوّتوا",
    poll_sticky_message_new_poll: "استطلاع جارٍ بواسطة {author}: ",
    poll_sticky_message_me_voted: "تصويتي: {answerText}",
    poll_sticky_message_me_not_voted: "النقر للتصويت",
    poll_fallback_link_text: "Skype لويب",
    poll_list_title: "تم التصويت من قبل ({count})",

    presence_lastseen_moments: "آخر ظهور منذ لحظات",
    presence_lastseen_minutes: "آخر ظهور منذ {number} من الدقائق",
    presence_lastseen_hours: "آخر ظهور منذ {number} من الساعات",
    presence_lastseen_days: "آخر ظهور منذ {number} من الأيام",

    presence_lastseen_date_short: "آخر ظهور في {shortdate}",
    presence_lastseen_date_full: "آخر ظهور في {fulldate}",

    guest_user_displayname: "(الضيف) {displayName}",
    pes_featured_title: "العناصر المميزة",
    //Call to action for the moji play button
    pes_moji_playbutton_label: "النقر للتشغيل",

    label_jumpToConversation: "الانتقال إلى المحادثة",

    share_on_skype_dialog_title: "المشاركة على Skype",
    share_on_skype_share_button: "مشاركة",
    share_on_skype_alt_text_button: "المشاركة على Skype",

    share_on_skype_message_prompt: "تضيمن رسالة حول هذا الشأن...",
    share_on_skype_picker_prompt: "بحث أو تحديد...",
    share_on_skype_status_sending: "يتم الآن الإرسال...",
    share_on_skype_status_sent: "تم الإرسال",

    share_on_skype_signed_in_as: "تم تسجيل الدخول كـ {displayName}",
    share_on_skype_my_account: "حسابي",
    share_on_skype_sign_out: "تسجيل الخروج",

    file_transfer_file_shared: "تمت مشاركة ملف",
    file_transfer_share_file: "مشاركة ملف",
    file_transfer_send_photos_and_files: "إرسال صور وملفات",
    file_transfer_download_button_title: "تنزيل الملف {filename}",
    file_transfer_download_dialog_confirm_button_title: "قبول",
    file_transfer_download_unsafe_file_dialog_title: "تحذير - قد يكون هذا الملف غير آمن للاستخدام على الكمبيوتر/الجهاز.",
    file_transfer_download_unsafe_file_dialog_text: "هل تريد قبول الملف {filename} من {author}؟",
    file_transfer_download_safe_file_dialog_title: "قبول ملفات من الأشخاص الذين تثق بهم فقط.",
    file_transfer_download_safe_file_dialog_text: "هل تريد قبول الملف {filename} من {author}؟",
    file_transfer_download_dialog_do_not_ask_checkbox: "لا تسألني مرة أخرى",
    file_transfer_upload_state: "{uploaded} من أصل {size}",
    file_transfer_upload_completed: "تم تحميل الملف {filename}",
    file_transfer_upload_failed: "تعذر تحميل الملف",
    file_transfer_upload_canceled: "تم إلغاء عملية التحميل",
    file_transfer_upload_cancel: "إلغاء التحميل",
    file_transfer_upload_too_large_warning: "لم يتم الإرسال - الملف أكبر من 100 ميغابايت. <a href='http://go.skype.com/Cloud.File.Upload' target='_blank'>اكتشف المزيد</a>",
    file_transfer_upload_starting: "بدء التحميل",
    file_transfer_upload_not_supported: "لا يتم دعم مشاركة الملفات على Skype لويب",

    notificationsPage_text_menuLink: "الإعلامات",
    remove_conversation_confirmation_text: "سيتم حذف كل الرسائل في هذه المحادثة وستتم إزالتها من الشريط الجانبي ومحفوظاتك.",
    remove_conversation_confirmation_text_4b: "ستغادر هذه المحادثة وستتم إزالتها من الشريط الجانبي.",
    remove_conversation_confirmation_title: "هل تريد بالتأكيد حذف هذه المحادثة؟",
    remove_conversation_confirmation_title_4b: "هل تريد بالتأكيد إغلاق هذه المحادثة؟",
    accessibility_remove_conversation_confirmation: "تم حذف المحادثة",
    leave_conversation_confirmation_text: "‏‏لا يمكن التراجع عن هذا الإجراء.",
    leave_conversation_confirmation_text_4b: "لن تتلقى أي إعلامات إضافية من هذه المحادثة. يمكنك إعادة الانضمام لاحقاً عبر إرسال رسالة جديدة.",
    leave_conversation_confirmation_title: "هل تريد بالتأكيد مغادرة \"{topic}\"؟",
    leave_conversation_confirmation_title_4b: "هل تريد بالتأكيد مغادرة المحادثة؟",

    contact_information_already_contact: "جهة اتصال بالفعل",
    contact_information_add_to_contacts: "إضافة إلى جهات الاتصال",
    mediaBar_sendContacts_label: "إرسال جهات الاتصال...",
    contactPicker_sendContacts_title: "إرسال جهات اتصال",
    contactPicker_sendContacts_OKBUtton: "إرسال",
    chat_contactSent_label: "تم إرسال جهة الاتصال",
    chat_contactSent_iconLabel: "تم الإرسال",
    mention_notification_title: "تمت الإشارة إليك في {chat} من قبل {participant}",
    contextMenu_picture_viewAction: "عرض",
    contextMenu_picture_commentAction: "تعليق",
    contextMenu_picture_downloadAction: "تنزيل",
    contextMenu_text_discussAction: "مناقشة",

    send_contacts_action_title: "إرسال جهات اتصال",
    send_contacts_action_text: "إضافة جهات اتصال ترغب في إرسالها",

    invite_free_overlay_greeting: "إلقاء التحية على",
    invite_free_bubble_contact: "اكتب رسالة هنا",
    invite_free_bubble_non_contact: "اكتب رسالةً هنا، ثم انتظر تلقي رد.",
    invite_free_textarea_waiting_for_reply: "بانتظار رد...",
    invite_free_message_received: "تم إرسال رسالة إليك من قِبل <strong>{displayName}</strong>",
    invite_free_message_received_location: "تم إرسال رسالة إليك من قِبل <strong>{displayName}</strong> من {location}",
    invite_free_block_person: "حظر هذا الشخص",
    invite_free_respond_request: "يجب كتابة أي رسالة لقبول جهة الاتصال هذه",

    me_pluginLinkText: "تنزيل مكون Skype الإضافي",
    me_accountLinkText: "إدارة الحساب",
    me_accountSignOutLinkText: "تسجيل الخروج",
    me_pendingPresence: "جارٍ عرض الحالة...",
    me_help: "تعليمات",
    me_skypeCommunity: "مجتمع Skype",
    me_sendFeedback: "إرسال الملاحظات",
    me_mood: "المزاج",
    me_status: "الحالة",
    me_accountInfo: "معلومات الحساب",
    me_notifications: "الإعلامات",
    me_mobileNumber: "رقم الهاتف المحمول",

    me_avatar_uploadProfilePictureText: "تحميل صورة ملف تعريف",
    group_avatar_uploadProfilePictureText: "تحميل صورة دردشة جماعية",
    me_avatar_uploadProfilePictureAriaLabel: "تحميل صورة كرتونية",

    me_edit_activity_message: "تحرير رسالة النشاط",
    me_activity_message_title: "النشاط الحالي",
    me_input_text_activity_message_placeholder: "تغيير رسالة النشاط",
    me_edit_activity_message_confirm: "حفظ التغييرات",
    me_edit_activity_message_cancel: "إلغاء التغييرات",

    accessibility_me_changePresenceStatusAriaLabel: "تغيير حالة الحضور على الإنترنت (حالياً {currentStatus})",

    message_sent_status: "تم الإرسال",
    message_sending_status: "يتم الإرسال",
    message_delivered_status: "تم التسليم",
    message_read_status: "مقروءة",
    message_failed_status: "فشل الإرسال",

    message_edited_success: "تم تحرير الرسالة",
    message_removed_success: "تمت إزالة الرسالة",

    credit_balance_text: "رصيد Skype التابع لك",
    credit_purchase_link_text: "إضافة رصيد Skype",
    subscription_entitlement_text: "الاشتراكات",
    subscription_purchase_link_text: "الحصول على اشتراك",
    no_subscriptions_text: "ليس لديك اشتراكات",
    subscriptions_text_one: "لديك اشتراك {count}",
    subscriptions_text_many: "لديك {count} من الاشتراكات",
    pstn_emergency_notice_text: "لا يُعتبر Skype لويب (الإصدار التجريبي) بديلاً لهاتفك ولا يمكن استخدامه لإجراء مكالمات الطوارئ.",
    pstn_insufficient_funds: "تعذّر الاتصال، يجب أن يتوفر لديك {credit} أو {subscription} للاتصال بالخطوط الأرضية والهواتف المحمولة من Skype.",
    pstn_insufficient_funds_credit: "رصيد Skype",
    pstn_insufficient_funds_subscription: "اشتراك",
    pstn_invalid_number: "الرقم الذي طلبته غير صالح.",
    pstn_invalid_number_return_link: "يرجى العودة إلى \"الاتصال بالهواتف\" والمحاولة مرة أخرى.",
    pstn_forbidden_number: "يتعذر الاتصال بالرقم الذي طلبته باستخدام Skype.",
    pstn_insufficient_funds_group: "تعذر على مشترك {phoneNumber} الانضمام إلى المكالمة. يجب توفر {credit} أو {subscription} لإضافته إلى المكالمة.",
    pstn_insufficient_funds_group_name: "تعذر على مشترك {displayName} ‏(‏{phoneNumber}) الانضمام إلى المكالمة. يجب توفر {credit} أو {subscription} لإضافته إلى المكالمة.",
    pstn_invalid_number_group: "تعذر على مشترك {phoneNumber} الانضمام إلى المكالمة لأنّ الرقم غير صالح.",
    pstn_invalid_number_group_name: "تعذر على مشترك {displayName} ‏(‏{phoneNumber}) الانضمام إلى المكالمة لأنّ الرقم غير صالح.",
    pstn_forbidden_number_group: "تعذر على مشترك {phoneNumber} الانضمام إلى المكالمة إذ لا يمكن الاتصال بالرقم باستخدام Skype.",
    pstn_forbidden_number_group_name: "تعذر على مشترك {displayName} ‏({phoneNumber}) الانضمام إلى المكالمة إذ لا يمكن الاتصال بالرقم باستخدام Skype.",

    hearts_bubble_title: "الأشخاص الذين سجلوا إعجابهم بهذا",
    hearts_bubble_meliked: "أنت",
    hearts_loved_by: "{list}",
    hearts_loved_by_count: "أحبه {count}",
    hearts_loved_by_others: "أحبه {list} و<span>‏‎{count}&nbsp;من الأشخاص الآخرين</span>",

    hearts_list_title: "تم تسجيل الإعجاب من قِبل ({count})",
    hearts_me_text: "أنت",
    hearts_like_byMeOnly: "أعجبك هذا",
    hearts_like_byOne: "تم تسجيل الإعجاب بهذا من قِبل {participantName}",
    hearts_like_byFew: "تم تسجيل الإعجاب بهذا من قِبل {participantFirst}{list} و{participantLast}",
    hearts_like_byMany: "تم تسجيل الإعجاب بهذا من قِبل {participantlist} و<span>{count}&nbsp;آخرين</span>",
    hearts_notification_messageGroup: "تم تسجيل الإعجاب برسالتك {messageText} من قِبل {participantName}",
    hearts_notification_messageConv: "سجّل إعجابه برسالتك {messageText}",
    hearts_notification_photoGroup: "تم تسجيل الإعجاب بصورتك من قِبل {participantName}",
    hearts_notification_photoConv: "سجّل إعجابه بصورتك",
    hearts_notification_fileGroup: "تم تسجيل الإعجاب بملفك من قِبل {participantName}",
    hearts_notification_fileConv: "سجّل إعجابه بملفك",
    hearts_notification_documentGroup: "تم تسجيل الإعجاب بمستندك من قِبل {participantName}",
    hearts_notification_documentConv: "سجّل إعجابه بمستندك",
    hearts_notification_videoMessageGroup: "تم تسجيل الإعجاب برسالة الفيديو الخاصة بك من قِبل {participantName}",
    hearts_notification_videoMessageConv: "سجّل إعجابه برسالة الفيديو الخاصة بك",
    hearts_notification_urlGroup: "تم تسجيل الإعجاب بعنوان url الخاص بك من قِبل {participantName}",
    hearts_notification_urlConv: "سجّل إعجابه بعنوان url الخاص بك",
    hearts_notification_youTubeGroup: "تم تسجيل الإعجاب بفيديو YouTube الذي نشرته من قِبل {participantName}",
    hearts_notification_youTubeConv: "سجّل إعجابه بفيديو YouTube الذي نشرته",

    hearts_accessibility_like: "تسجيل الإعجاب بالرسالة",
    hearts_accessibility_unlike: "إلغاء تسجيل الإعجاب بالرسالة",

    hearts_toast_message: "جديد",
    hearts_toast_title: "النقر للانتقال إلى الرسالة التي تم تسجيل الإعجاب بها",
    me_notificationsOn: "تشغيل الإعلامات",
    me_notificationsOff: "إيقاف تشغيل الإعلامات",

    education_bubble_search: "ابحث عن أشخاص للاتصال بهم والدردشة معهم، ويمكنك البحث بواسطة البريد الإلكتروني أو اسم Skype.",
    education_bubble_search_4b: "انقر فوق هذا الزر للبحث عن أشخاص للدردشة معهم.",
    education_bubble_search_title_4b: "البحث عن جهة اتصال",
    education_bubble_call: "حدد زر الكاميرا لبدء مكالمة فيديو.",
    education_bubble_chat: "اختر جهة اتصال لبدء دردشة أو مكالمة.",
    education_bubble_chat_4b: "انقر فوق جهة اتصال لإرسال رسالة إليها.",
    education_bubble_chat_title_4b: "إرسال رسالة فورية",
    education_bubble_gotit_button_4b: "فهمت",
    education_bubble_schedule_call_1: "جدوِل مكالمتك التالية مع {name} هنا.",
    education_bubble_schedule_call_1_group: "ابقَ على اتصال وجدوِل مكالمتك التالية هنا.",

    schedule_call_new_conversation_topic: "مكالمة Skype",
    schedule_call_subject_text: "مكالمة Skype مع {topic}",

    welcomeDialog_header: "أهلاً بك في Skype لويب (الإصدار التجريبي)",
    welcomeDialog_getInTouch: "تواصل مع أصدقائك وأفراد عائلتك مباشرةً من المستعرض",
    welcomeDialog_sendIM: "أرسل رسائل فورية",
    welcomeDialog_makeCalls: "أجرِ مكالمات Skype",
    welcomeDialog_makeVideoCalls: "أجرِ مكالمات فيديو",
    welcomeDialog_getStarted_button: "ابدأ الاستخدام",
    welcomeDialog_notForEmergencyCalls: "لا يُعتبر Skype لويب (الإصدار التجريبي) بديلاً لهاتفك ولا يمكن استخدامه لإجراء مكالمات الطوارئ.",
    welcomeDialog_cookiesConsent: "باستخدام هذا الموقع، توافق على استخدام ملفات تعريف الارتباط للتحليلات والمحتوى الشخصي والإعلانات.",
    welcomeDialog_readMore: "اقرأ المزيد حول ملفات تعريف الارتباط",

    modal_scheduleCall_getting_ready_label: "جارٍ إعداد مكالمتك...",
    modal_scheduleCall_ready_label: "أصبحت مكالمتك جاهزة للجدولة.",
    modal_scheduleCall_create_event_button: "إنشاء حدث",
    modal_scheduleCall_close_button: "إغلاق",

    cqf_title: "كيف تصنف جودة هذه المكالمة؟",
    cqf_audio_title: "أعلمنا بأي مشاكل واجهتها في الصوت. سنستخدم الملاحظات لتحسين Skype.",
    cqf_video_title: "أعلمنا بأي مشاكل واجهتها في الصوت أو الفيديو. سنستخدم الملاحظات لتحسين Skype.",
    cqf_audio_tokens_title: "الصوت",
    cqf_video_tokens_title: "الفيديو",
    cqf_audio_nolocal: "لم أسمع أي صوت",
    cqf_audio_noremote: "لم تسمع الجهة الأخرى أي صوت",
    cqf_audio_quality_echo: "سمعت صدىً في المكالمة",
    cqf_audio_quality_noise: "سمعت ضجيجاً في المكالمة",
    cqf_audio_quality_volume: "كان مستوى الصوت منخفضاً",
    cqf_audio_dropped: "انتهت المكالمة بشكل غير متوقع",
    cqf_audio_quality_distorted: "لم يكن الكلام طبيعياً أو بدا مشوهاً",
    cqf_audio_quality_delay: "استمرّينا في مقاطعة بعضنا البعض",
    cqf_audio_other: "غير ذلك، يرجى التحديد",
    cqf_audio_quality_dialpad: "لم تعمل نغمات لوحة الطلب",
    cqf_video_nolocal: "لم أرَ أي فيديو",
    cqf_video_noremote: "لم ترَ الجهة الأخرى الفيديو التابع لي",
    cqf_video_quality_poor: "كانت جودة الصورة رديئة",
    cqf_video_quality_freezing: "استمر الفيديو في التوقف",
    cqf_video_dropped: "توقف الفيديو بشكل غير متوقع",
    cqf_video_quality_dark: "كانت الإضاءة لدى الجهة الأخرى قاتمة جداً",
    cqf_video_quality_sync: "كان الفيديو يسبق الصوت أو يتأخر عنه",
    cqf_video_other: "غير ذلك، يرجى التحديد",
    cqf_thanks_title: "شكراً على ملاحظاتك!",

    cqf_accessibility_cancel_btn: "إلغاء الأمر",
    cqf_accessibility_submit_btn: "إرسال الملاحظات",
    cqf_accessibility_oneStar_ariaLabel: "سيئة جداً",
    cqf_accessibility_twoStars_ariaLabel: "ضعيفة",
    cqf_accessibility_threeStars_ariaLabel: "مقبولة",
    cqf_accessibility_fourStars_ariaLabel: "جيدة",
    cqf_accessibility_fiveStars_ariaLabel: "ممتازة",

    unanswered_call_title_busy: "مشغول",
    unanswered_call_accessibility_title_busy: "المتصَل به مشغول.",
    unanswered_call_title_noanswer: "لم يتم الرد",
    unanswered_call_accessibility_title_noanswer: "لم يُجب المتصَل به.",
    unanswered_call_title_unavailable: "غير متوفر",
    unanswered_call_accessibility_title_unavailable: "الاتصال غير متوفر.",
    unanswered_call_button_chat: "رسالة محادثة",
    unanswered_call_accessibility_button_chat: "رسالة محادثة",
    unanswered_call_button_retry: "إعادة المحاولة",
    unanswered_call_accessibility_button_retry: "إعادة المحاولة",
    unanswered_call_button_close: "إغلاق",
    unanswered_call_accessibility_button_close: "إغلاق",
    unanswered_call_button_showchat: "إظهار الدردشة",
    unanswered_call_accessibility_button_showchat: "إظهار الدردشة",
    unanswered_call_chatinput_placeholder: "يرجى معاودة الاتصال بي (call)", // (call) is the shortcut for the calling emoticon
    unanswered_call_dial_number: "رقم الاتصال",

    favorites_recents_category_name: "المفضلة",
    favorites_add_to_favorite: "إضافة إلى المفضلة",
    favorites_remove_from_favorite: "إزالة من المفضلة",

    welcome_im_display_name: "إرسال رسائل فورية في Outlook",
    welcome_im_toast_message: "أصبح بإمكانك الآن إرسال رسائل فورية من Outlook.‏\r\n\r\n",
    welcome_im_first_message: "اكتب رسالة أدناه واضغط على Enter لرؤية النتيجة.\r\n\r\nلمزيد من المرح، أضف بعضاً من هذه الرموز :) B-) :D",
    welcome_im_reply_message: "(clap) رائع! أصبحت جاهزاً الآن للمراسلة.",

    sms_input_text_message: "اكتب رسالة SMS هنا",
    sms_via_text: "عبر",
    sms_message_destination_skype: "Skype",
    sms_message_destination_sms: "رسالة SMS {phone}",
    sms_add_phone_number: "إضافة رقم هاتف...",
    sms_country_all_recent_codes_group_title: "البلدان/المناطق الأخيرة",
    sms_country_all_country_codes_group_title: "جميع البلدان والمناطق",
    sms_add_phone_number_dialog_text: "إضافة رقم من أجل {accountDisplayName}",
    sms_send_sms_to_section_title: "إرسال SMS إلى:",
    sms_settings_identification_section_title: "عندما أرسل رسالة SMS، تعرّف علي بواسطة:",
    sms_settings_identification_section_option1: "اسم Skype الخاص بي ({skypeid}). لا يمكن للمستلمين إرسال ردود على رسائل SMS.",
    sms_settings_identification_section_option2: "رقم هاتفي المحمول. يمكن للمستلمين إرسال ردود على رسائل SMS.",
    sms_settings_destination_and_rates_link_text: "وجهات وأسعار رسائل SMS",
    sms_settings_learnmore_link_text: "معرفة المزيد عن رسائل SMS",
    sms_turn_off_sms_sending: "إرسال عبر Skype",
    sms_status_sending: "يتم إرسال رسالة SMS",
    sms_status_delivered: "تم تسليم رسالة SMS",
    sms_status_deliveringError: "فشل تسليم رسالة SMS",

    sms_insufficient_balance: "تحتاج إلى رصيد Skype لإرسال رسائل SMS",
    sms_price_info_failed: "حدث خطأ أثناء جلب أسعار رسائل SMS.",
    sms_price_info_bad_number: "الرقم الذي تريد إرسال رسالة SMS إليه غير صحيح",
    sms_price_info_bad_number_account: "تعذر الحصول على المعلومات المتعلقة بالأسعار للرقم المعطى",

    unreadConversationsReminder: "لديك {count}محادثة غير مقروءة",
    unreadConversationsReminder_few: "لديك {count} من المحادثات غير مقروءة",
    unreadConversationsReminder_many: "لديك {count} من المحادثات غير مقروءة",

    unreadMessageFromPersonAndOthersReminder: "لديك رسائل غير مقروءة من  {name} و{count} آخرين",
    unreadMessageFromPersonAndOthersReminder_few: "لديك رسائل غير مقروءة من {name} و {count} آخرين",
    unreadMessageFromPersonAndOthersReminder_many: "لديك رسائل غير مقروءة من {name} و {count} آخرين",

    unreadMessageFromPersonReminder: "لديك رسائل غير مقروءة من {name}",

    unreadMessageInGroupAndOthersReminder: "لديك رسائل غير مقروءة حول {topic} و {count} أخرى",
    unreadMessageInGroupAndOthersReminder_few: "لديك رسائل غير مقروءة حول {topic} و {count} أخرى",
    unreadMessageInGroupAndOthersReminder_many: "لديك رسائل غير مقروءة حول {topic} و {count} أخرى",

    unreadMessageInGroupReminder: "لديك رسائل غير مقروءة حول {topic} "
});
